FlipsideCrypto/livequery-models

.gitignore, .sqlfluff, .sqlfluffignore, README.md, analysis/test_create_or_drop_function_from_config.sql, cspell.yml, dbt_project.yml, macros/create_udfs.sql, macros/streamline/api_integrations.sql, macros/streamline/configs.yaml.sql, macros/streamline/streamline_udfs.sql, macros/streamline/utils.sql, packages.yml
- create utility macros for creating udfs
- new udfs
- udf_api
- streamline.introspect
- streamline.whoami
- streamline.udf_register_secret
- beta.udf_register_secret
- streamline.udf_api
- beta.udf_api
- add sqlfluff
=> LiveQuery Beta Release

README.md, analysis/test_functions.sql, analysis/test_functions_py.sql, macros/streamline/configs.yaml.sql, macros/streamline/functions.sql
- add utils.udf_json_rpc_call
- add convenience overrides for live.udf_api
- add tests for new macros udfs
=> AN-2979/udf-json-rpc-call

macros/streamline/configs.yaml.sql, macros/streamline/functions.py.sql
- adds `udf_keccak256` and `udf_evm_text_signature`
=> add evm utils

.github/workflows/dbt_run_adhoc.yml, .github/workflows/dbt_test.yml, dbt_project.yml, macros/core/utils.yaml.sql, macros/livequery/manage_udfs.sql, macros/marketplace/opensea/udfs.yaml.sql, macros/marketplace/reservoir/udfs.yaml.sql, models/deploy/core/utils.yml, models/deploy/marketplace/opensea/opensea__.sql, models/deploy/marketplace/opensea/opensea__.yml, models/deploy/marketplace/reservoir/reservoir__.sql, models/deploy/marketplace/reservoir/reservoir__.yml
This PR integrates Reservoir and OpenSea into LiveQuery. It also includes tests for both providers. 
**Examples:**
- [OpenSea](https://flipsidecrypto.xyz/edit/queries/0e4f856c-0b9f-47c9-a237-b62a9d08e8a0): 
- [Reservoir](https://flipsidecrypto.xyz/edit/queries/21af6918-0e22-4250-a522-6f101275023a)
=> Integrate Reservoir and OpenSea

.github/workflows/dbt_test.yml, macros/marketplace/stakingrewards/udfs.yaml.sql, models/deploy/marketplace/stakingrewards/stakingrewards__ .yml, models/deploy/marketplace/stakingrewards/stakingrewards__.sql
This PR integrates the Staking Rewards GraphQL capabilities with LiveQuery. This also includes tests. 
Flipside Function Guide [here](https://flipsidecrypto.xyz/edit/queries/6ef42233-8566-4f3f-906e-997e5189b282).
=> StakingRewards Integration

.github/workflows/dbt_test.yml, macros/marketplace/helius/das_udfs.yaml.sql
This PR fixes an issue where the wrapper function was not calling the correct RPC method.
=> Fix issue with Helius DAS function getAssetsByGroup

.github/workflows/dbt.yml, .github/workflows/dbt_test.yml
- create resuable dbt job
- update test workflow to use dbt workflow
=> Resuable workflows for tests

.github/workflows/dbt.yml, .github/workflows/dbt_test.yml
- move env variables to called workflow
=> STREAM-412 - move env variables to called workflow

.github/workflows/dbt.yml, .github/workflows/dbt_run_adhoc.yml, .github/workflows/dbt_run_dev_refresh.yml, .github/workflows/dbt_test.yml
use resusable dbt workflow
- refactor dev_refresh workflow
- refactor run_adhoc workflow
=> Cleanup Workflows 

.github/workflows/dbt_test.yml, macros/marketplace/apilayer/udfs.yaml.sql, macros/marketplace/deepnftvalue/udfs.yaml.sql, macros/marketplace/snapshot/udfs.yaml.sql, macros/marketplace/solscan/udfs.yaml.sql, macros/marketplace/zapper/udfs.yaml.sql, models/deploy/marketplace/apilayer/apilayer__.sql, models/deploy/marketplace/apilayer/apilayer__.yml, models/deploy/marketplace/deepnftvalue/deepnftvalue__.sql, models/deploy/marketplace/deepnftvalue/deepnftvalue__.yml, models/deploy/marketplace/snapshot/snapshot__ .yml, models/deploy/marketplace/snapshot/snapshot__.sql, models/deploy/marketplace/solscan/solscan__.sql, models/deploy/marketplace/solscan/solscan__.yml, models/deploy/marketplace/zapper/zapper__.sql
**This PR Adds 5 New Integrations:**
1. **Zapper** - `_FSC_SYS/ZAPPER`, example code: [https://flipsidecrypto.xyz/edit/queries/b6c475c7-40b5-4943-841f-5998e88c4a3e](https://flipsidecrypto.xyz/edit/queries/b6c475c7-40b5-4943-841f-5998e88c4a3e)
2. **Snapshot** - no secret, example code: [https://flipsidecrypto.xyz/edit/queries/ed964fb4-7bc6-4ce0-a437-2aa9914cb138](https://flipsidecrypto.xyz/edit/queries/ed964fb4-7bc6-4ce0-a437-2aa9914cb138)
3. **Solscan** - `_FSC_SYS/SOLSCAN`, example code: [https://flipsidecrypto.xyz/edit/queries/07077465-1103-4632-91a6-6773a0878a82](https://flipsidecrypto.xyz/edit/queries/07077465-1103-4632-91a6-6773a0878a82)
4. **DeepNFTValue** - `_FSC_SYS/DEEPNFTVALUE`, example code: [https://flipsidecrypto.xyz/edit/queries/450096b8-32cb-4c81-91f7-497669c3eafb](https://f …
=> 5 New Integrations

.github/workflows/dbt_test.yml, macros/marketplace/quicknode/util_udfs.yaml.sql
- fix solana secret name for quicknode_utils.solana_mainnet_rpc
=> - fix solana secret name for quicknode_utils.solana_mainnet_rpc

dbt_project.yml, macros/core/_utils.yaml.sql, macros/core/secrets.yaml.sql, models/deploy/core/secrets.sql, models/deploy/core/secrets.yml
- create secrets udfs for enterprise users
- added feature flag to selectively enable udfs
=> Udfs for managing secrets

dbt_project.yml, macros/grants.sql, macros/marketplace/defillama/udfs.yaml.sql, models/deploy/core/_utils.yml, models/mapping_tables/_eth__decoded_logs.sql, models/mapping_tables/_eth__logs.sql, models/mapping_tables/_evm__abi_map.sql, models/mapping_tables/_evm__contracts_map.sql, models/mapping_tables/_evm__native_symbol_map.sql
- fix roles interoplation bug with refactored dbt project vars
- set headers for defillama
=> STREAM-674/bugs-defillama-project-vars

dbt_project.yml
=> revert tag changes

dbt_project.yml, models/deploy/core/secrets.sql
- use model config to disable test instead of conditional jinja
=> Fix Secrets Schema Test compile bug

.github/workflows/dbt_integration_test.yml, .github/workflows/dbt_udf_test.yml, macros/marketplace/defillama/udfs.yaml.sql
- use github environment var *WAREHOUSE* for workflows instead of hardcoded value
- DeFiLLama integration updated to include secret for api_key query parameter
=> LiveQuery DeFiLLama Api key integration, workflow updates for Warehouse

.github/workflows/dbt_run_adhoc.yml
add xsmall warehouse from hosted environment
=> LiveQuery Add hosted warehouse

.github/workflows/dbt.yml, profiles.yml, requirements.txt
set environment variables conditionally based on dispatch event
abstract target to environment variable
use input variable for python version
=> GHA workflow cleanup

.github/workflows/dbt.yml, .github/workflows/dbt_integration_test.yml
use job concurrency
use fallback instead of conditional workflow step
=> Tweak workflow

.github/workflows/dbt_integration_test.yml
cleanup `.github/workflows/dbt_integration_test.yml`
=> Workflow cleanup

.github/workflows/dbt.yml, .github/workflows/dbt_integration_test.yml
cleanup `.github/workflows/dbt_integration_test.yml` (#68)
=> GHA workflow fix

.github/workflows/dbt_integration_test.yml
=> fix matrix

.github/workflows/dbt.yml
=> LiveQuery GHA Artifact Names

macros/core/live.yaml.sql, models/live__allow_list.sql
=> LiveQuery - Live view to show allowed apis

macros/core/functions.py.sql
1. Updates udf logic to better handle leading zeros
2. Requires adhoc run `dbt run -m models/deploy/core/utils.sql --vars '{"UPDATE_UDFS_AND_SPS":true, DROP_UDFS_AND_SPS: false}'`
=> AN-4890/base58-update

macros/marketplace/claude/messages_batch_udfs.yaml.sql, macros/marketplace/claude/messages_udfs.yaml.sql, macros/marketplace/claude/models_udfs.yaml.sql, selectors.yml
Fix the claude udf schema to match the doc that is already deploy
=> Update Claude UDF schema names to standardize to "claude"

.github/workflows/dbt_udf_test.yml, macros/marketplace/alchemy/nft_udfs.yaml.sql, macros/marketplace/claude/messages_udfs.yaml.sql, models/deploy/marketplace/claude/claude__.yml
1. Remove duplicated udfs in claude & claude_utils
2. Fix type signature type in CHECK TOKEN claude udf
3. Fix Alchemy nft reingest endpoint to new version to v3
4. Add Environment when the test_udf runs
(ENV) - (Branch)
if it's pull_request: dev - PR's Title
if it's scheduled: prod - main
if it's workflow dispatch: input env -  input branch
Example: https://github.com/FlipsideCrypto/livequery-models/actions/runs/13804920
291
=> Fix: failing tests in livequery marketplace

macros/marketplace/helius/util_udfs.yaml.sql
This updates the helius rpc url to the one in mainnet.
Ref: https://docs.helius.dev/rpc/http
=> [STREAM-1178] update helius rpc url to mainnet

macros/core/_live.yaml.sql, macros/core/live.yaml.sql, macros/livequery/udf_compatibility.sql, macros/marketplace/alchemy/util_udfs.yaml.sql, macros/marketplace/claude/util_udfs.yaml.sql, macros/marketplace/github/actions_udtfs.yml.sql, macros/marketplace/github/utils_udfs.yaml.sql, macros/marketplace/helius/apis_udfs.yaml.sql, macros/marketplace/helius/util_udfs.yaml.sql, macros/marketplace/slack/utils_udfs.yaml.sql, models/deploy/core/_external_access.sql, models/deploy/core/live.yml
- Updated UDF definitions to utilize the new `is_udf_api_v2_compatible()` macro for compatibility checks, replacing the previous `check_udf_api_v2_exists()` method.
- Refactored SQL logic across multiple UDFs to improve clarity and maintainability.
- Added conditional checks for UDF API version compatibility in various macros, ensuring backward compatibility and improved functionality.
- Enhanced comments and documentation for better understanding and maintainability of the codebase.
=> [STREAM-1324] Enhance UDF compatibility checks and refactor UDF definitions
